import config from '../config.cjs';

const groupCommands = async (Matrix, m) => {
    const prefix = config.PREFIX;
    const body = m.body || "";
    const cmd = body.startsWith(prefix) ? body.slice(prefix.length).trim().split(/\s+/)[0].toLowerCase() : "";
    const args = body.slice(prefix.length + cmd.length).trim().toLowerCase();

    if (!m.isGroup) return;

    // Modern branding configuration
    const channelConfig = {
        newsletterJid: '120363406146813524@newsletter',
        newsletterName: "TIMNASA TMD • ELITE",
        serverMessageId: 143
    };

    try {
        const groupMetadata = await Matrix.groupMetadata(m.from);
        const participants = groupMetadata.participants;
        const botNumber = await Matrix.decodeJid(Matrix.user.id);
        
        const isBotAdmin = participants.find(p => p.id === botNumber)?.admin;
        const isSenderAdmin = participants.find(p => p.id === m.sender)?.admin;
        const isOwner = config.OWNER.includes(m.sender.split('@')[0]) || m.isOwner;

        // Security Helper
        const checkPerms = () => {
            if (!isOwner && !isSenderAdmin) {
                m.reply("*⚠️ ACCESS DENIED:* Admins only.");
                return false;
            }
            if (!isBotAdmin) {
                m.reply("*📛 BOT ERROR:* I need *Admin* rights.");
                return false;
            }
            return true;
        };

        // --- COMMANDS ---
        switch (cmd) {

            case 'invite':
                if (!checkPerms()) return;
                const code = await Matrix.groupInviteCode(m.from);
                m.reply(`*🔗 GROUP INVITE LINK*\n\nhttps://chat.whatsapp.com/${code}\n\n*Generated by Timnasa Tmd*`);
                break;

            case 'tagnation':
                if (!checkPerms()) return;
                let tagMsg = `*🌍 TAGNATION - GLOBAL MENTION*\n\n*Message:* ${args || "No Message Provided"}\n\n`;
                participants.forEach(mem => tagMsg += `📍 @${mem.id.split('@')[0]}\n`);
                Matrix.sendMessage(m.from, { 
                    text: tagMsg, 
                    mentions: participants.map(a => a.id),
                    contextInfo: { forwardedNewsletterMessageInfo: channelConfig, isForwarded: true }
                }, { quoted: m });
                break;

            case 'terminateall':
                // Extremely Dangerous Command: Restricted to OWNER only
                if (!isOwner) return m.reply("*❌ SECURITY ALERT:* This command is restricted to the *Bot Owner* only.");
                if (!isBotAdmin) return m.reply("*📛 ERROR:* Bot needs Admin to terminate.");

                m.reply("☢️ *TERMINATION INITIALIZED:* Removing all members...");
                
                const membersToTerminate = participants.filter(p => p.id !== botNumber && p.id !== m.sender);
                for (let member of membersToTerminate) {
                    await Matrix.groupParticipantsUpdate(m.from, [member.id], 'remove');
                    // Delay to prevent WhatsApp ban
                    await new Promise(resolve => setTimeout(resolve, 1000)); 
                }
                m.reply("✅ *TERMINATION COMPLETE:* Group has been cleared.");
                break;

            case 'antilink':
                if (!checkPerms()) return;
                if (args === 'on') {
                    config.ANTILINK = true;
                    m.reply("✅ *ANTI-LINK ENABLED*");
                } else if (args === 'off') {
                    config.ANTILINK = false;
                    m.reply("❌ *ANTI-LINK DISABLED*");
                }
                break;

            case 'kick':
                if (!checkPerms()) return;
                let userToKick = m.quoted ? m.quoted.sender : m.mentionedJid[0];
                if (!userToKick) return m.reply("❌ Tag the user.");
                await Matrix.groupParticipantsUpdate(m.from, [userToKick], 'remove');
                m.reply("✅ Removed.");
                break;

            case 'promote':
                if (!checkPerms()) return;
                let userToPromote = m.quoted ? m.quoted.sender : m.mentionedJid[0];
                await Matrix.groupParticipantsUpdate(m.from, [userToPromote], 'promote');
                m.reply("🎊 Promoted.");
                break;

            case 'mute':
                if (!checkPerms()) return;
                await Matrix.groupSettingUpdate(m.from, 'announcement');
                m.reply("🔒 *GROUP CLOSED*");
                break;

            case 'unmute':
                if (!checkPerms()) return;
                await Matrix.groupSettingUpdate(m.from, 'not_announcement');
                m.reply("🔓 *GROUP OPENED*");
                break;
        }

    } catch (err) {
        console.error(err);
    }
};

export default groupCommands;
